---
- name: Postgres server containers 작동 시작
  hosts: airflow
  become: true
  vars:

    project_path: "/root/Police/postgres_server"

  tasks:
    - name: "Docker 네트워크 일괄 생성"
      community.docker.docker_network:
        name: "{{ item }}"
        state: present
      with_items:
        - trade_kospi_network
        - trade_kosdaq_network
        - trade_nasdaq_network
        - trade_nyse_network

    - name: "Postgres server containers"
      ansible.builtin.shell:
        cmd: "docker compose up -d"
        chdir: "{{ project_path }}"