---
- name: Docker Compose 배포 및 상태 확인
  hosts: airflow
  become: true
  vars:

    project_path: "/root/Police/postgres_server"

  tasks:
    - name: Run docker compose (Background)
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: present
        wait: true
      register: compose_output

    - name: Docker compose Results
      debug:
        msg: "Docker Compose가 성공적으로 실행되었습니다. (액션: {{ compose_output.actions }})"

    - name: Get Container information
      community.docker.docker_compose_v2_info:
        project_src: "{{ project_path }}"
      register: compose_info

    - name: Service summary
      debug:
        msg: "서비스 '{{ item.key }}'는 현재 '{{ item.value.state }}' 상태입니다."
      loop: "{{ compose_info.services | dict2items }}"
      loop_control:
        label: "{{ item.key }}" # 로그 출력 시 서비스 이름만 깔끔하게 표시