apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-airflow
  labels:
    service: airflow
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 10.15.0.170
    path: /root/nfs_node/airflow