apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-service
  namespace: was
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was-service
  template:
    metadata:
      labels:
        app: was-service
    spec:
      containers:
      - name: was-service
        image: yslee4050/fastapi:py39
        workingDir: /usr/share/nginx/html
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install --no-cache-dir pymysql pandas uvicorn
            uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
        ports:
        - containerPort: 8000
        - containerPort: 25
        - containerPort: 110
        - containerPort: 143
        volumeMounts:
        # nginx
        - name: data-vol
          mountPath: /usr/share/nginx/html
          subPath: was/yslee/web_interface
        - name: data-vol
          mountPath: /root/Data
          subPath: Data
        # MarketList
        - name: data-vol
          mountPath: /root/market
          subPath: was/yslee/postgres_server/market
        # MailServer
        - name: mail-vol
          mountPath: /mnt/mail_storage
      volumes:
      - name: data-vol
        nfs:
          server: 10.15.0.170
          path: /root/nfs_node
      - name: mail-vol
        nfs:
          server: 10.22.0.2
          path: /var/spool/mail
---
apiVersion: v1
kind: Service
metadata:
  name: was-service
  namespace: was
spec:
  selector:
    app: was-service
  ports:
    - name: http
      protocol: TCP
      port: 8000       # 서비스 포트
      targetPort: 8000 # 컨테이너 포트
    - name: smtp          # 메일 송신용
      protocol: TCP
      port: 25
      targetPort: 25
    - name: pop3          # 메일 수신용(다운로드)
      protocol: TCP
      port: 110
      targetPort: 110
    - name: imap          # 메일 수신용(동기화)
      protocol: TCP
      port: 143
      targetPort: 143
  type: ClusterIP # 내부 통신용