apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-service
  namespace: was
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was-service
  template:
    metadata:
      labels:
        app: was-service
    spec:
      containers:
      - name: was-service
        image: yslee4050/fastapi:py39
        workingDir: /usr/share/nginx/html
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install --no-cache-dir pymysql pandas uvicorn
            uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
        ports:
        - containerPort: 8000
        volumeMounts:
        # nginx
        - name: data-vol
          mountPath: /usr/share/nginx/html
          subPath: was/yslee/web_interface
        # KOSPI
        - name: data-vol
          mountPath: /root/Data/KOSPI/A1Sheet
          subPath: Data/KOSPI/A1Sheet
        - name: data-vol
          mountPath: /root/Data/KOSPI/B1Sheet
          subPath: Data/KOSPI/B1Sheet
        # KOSDAQ
        - name: data-vol
          mountPath: /root/Data/KOSDAQ/A1Sheet
          subPath: Data/KOSDAQ/A1Sheet
        - name: data-vol
          mountPath: /root/Data/KOSDAQ/B1Sheet
          subPath: Data/KOSDAQ/B1Sheet
        # NASDAQ
        - name: data-vol
          mountPath: /root/Data/NASDAQ/A1Sheet
          subPath: Data/NASDAQ/A1Sheet
        - name: data-vol
          mountPath: /root/Data/NASDAQ/B1Sheet
          subPath: Data/NASDAQ/B1Sheet
        # NYSE
        - name: data-vol
          mountPath: /root/Data/NYSE/A1Sheet
          subPath: Data/NYSE/A1Sheet
        - name: data-vol
          mountPath: /root/Data/NYSE/B1Sheet
          subPath: Data/NYSE/B1Sheet
        # MarketList
        - name: data-vol
          mountPath: /root/market
          subPath: was/yslee/postgres_server/market
        # MailServer
        - name: mail-vol
          mountPath: /mnt/mail_storage   
      volumes:
      - name: data-vol
        nfs:
          server: 10.15.0.170
          path: /root/nfs_node
      - name: mail-vol
        nfs:
          server: 10.22.0.2
          path: /mnt/mail_storage
---
apiVersion: v1
kind: Service
metadata:
  name: was-service
  namespace: was
spec:
  selector:
    app: was-service
  ports:
    - name: http
      protocol: TCP
      port: 8000       # 서비스 포트
      targetPort: 8000 # 컨테이너 포트
  type: ClusterIP # 내부 통신용