---
- name: Move specific file from one folder to another (Analysis)
  hosts: airflow  # 대상 서버 호스트 그룹명으로 변경 가능
  tasks:
    - name: Copy the file to the destination
      ansible.builtin.copy:
        src: /root/Police/daily_market/dag_analysis_kospi.py
        dest: /root/Cronjob/dags/dag_analysis_kospi.py
        mode: '0777'
    
    - name: Copy the file to the destination
      ansible.builtin.copy:
        src: /root/Police/daily_market/dag_analysis_kosdaq.py
        dest: /root/Cronjob/dags/dag_analysis_kosdaq.py
        mode: '0777'
    
    - name: Copy the file to the destination
      ansible.builtin.copy:
        src: /root/Police/daily_market/dag_analysis_nasdaq.py
        dest: /root/Cronjob/dags/dag_analysis_nasdaq.py
        mode: '0777'

    - name: Copy the file to the destination
      ansible.builtin.copy:
        src: /root/Police/daily_market/dag_analysis_nyse.py
        dest: /root/Cronjob/dags/dag_analysis_nyse.py
        mode: '0777'