---
- name: DNS 서버 완전 자동화 구축 
  hosts: dns_servers
  become: yes
  tasks:
    - name: 1. BIND 및 유틸리티 설치
      dnf:
        name: 
         - bind 
         - bind-utils
        state: present

    - name: 2. 백업파일 생성
      shell: |
        cp /etc/named.conf /etc/named.conf.bak
      ignore_errors: yes

    - name: 3. named.conf 자동 생성
      copy:
        dest: /etc/named.conf
        content: |
          options {
              listen-on port 53 { any; };
              directory "/var/named";
              allow-query { any; };
              recursion yes;
              dnssec-validation no;
          };
          include "/etc/named.kojel.zones";
        owner: root
        group: named
        mode: '0644'
