    server {
        listen 80;
        server_name kojel.com www.kojel.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name kojel.com www.kojel.com;
        charset utf-8;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
            root /usr/share/nginx/html;
            index login.html;
        }

        # API 요청을 WAS로 전달
        location /api {
            # [서비스이름].[네임스페이스].svc.cluster.local:[포트]
            proxy_pass http://was-service.was.svc.cluster.local:8000/;
           

            # 리버스 프록시 핵심 헤더 설정
            proxy_http_version 1.1; #연결 유지, 호환성을 위한 최신버전 사용
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            #웹소켓이나 실시간통신을 위한
            #proxy_http_version 1.1;
            #proxy_set_header Upgrade $http_upgrade;
            #proxy_set_header Connection "upgrade";
        }
    }