---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb:10.6
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: "P@ssw0rd"
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: nfs-db-volume
      mountPath: /var/lib/mysql
  volumes:
  - name: nfs-db-volume
    nfs:
      server: 10.15.0.170
      path: /nfs_k8s/db