---
- name: Airflow installation
  hosts: airflow
  become: yes
  vars:
    dest_path: "/root/Cronjob"
    airflow_version: "2.10.2"
    additional_packages: "finance-datareader pandas numpy psycopg2-binary"
    market_map_path: "/root/Police/postgres_server/market"

  tasks:
    - name: "Create airflow directory architecture"
      ansible.builtin.file:
        path: "{{ dest_path }}"
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: "Airflow directory subdirectories (dags, logs, plugins)"
      ansible.builtin.file:
        path: "{{ dest_path }}/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0777'
      with_items:
        - 'dags'
        - 'logs'
        - 'plugins'
      
    - name: "Get airflow docker-compose.yaml file"
      ansible.builtin.get_url:
        url: "https://airflow.apache.org/docs/apache-airflow/{{ airflow_version }}/docker-compose.yaml"
        dest: "{{ dest_path }}/docker-compose.yaml"
        mode: '0644'
        force: no

    - name: "Add market data volume to docker-compose.yaml"
      ansible.builtin.replace:
        path: "{{ dest_path }}/docekr-compose.yaml"
        regexp: '(\s+)- \$\{AIRFLOW_PROJ_DIR:-\.\}/plugins:/opt/airflow/plugins'
        replace: |
          \1- ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
          \1- {{ market_map_path }}:/opt/airflow/data/market
    
    - name: "Create .env file with AIRFLOW_UID"
      ansible.builtin.shell: |
        echo "AIRFLOW_UID=50000" > {{ dest_path }}/.env
        echo "_PIP_ADDITIONAL_REQUIREMENTS={{ additional_packages }}" >> {{ dest_path }}/.env
      args:
        creates: "{{ dest_path }}/.env"
    
    - name: "Initialize Airflow Database"
      ansible.builtin.shell:
        cmd: "docker compose up airflow-init"
        chdir: "{{ dest_path }}"
    
    - name: "Install airflow using docker-compose.yaml file"
      ansible.builtin.shell:
        cmd: "docker compose up -d --build" # --build 옵션 추가 권장
        chdir: "{{ dest_path }}"