apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: team-developer-role
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources: ["pods", "services", "deployments", "replicasets", "statefulsets", "ingresses", "jobs", "cronjobs", "secrets", "configmaps", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["*"] 

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
     
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

  - apiGroups: ["", "scheduling.k8s.io"]
    resources: ["nodes", "namespaces", "priorityclasses", "runtimeclasses"]
    verbs: ["get", "list", "watch"]