apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP  # 내부 통신용 IP 생성
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate  
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "root"
        - name: MARIADB_DATABASE
          value: "userdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql  # 데이터가 저장되는 실제 경로
      volumes:
      - name: db-data
        hostPath:
          path: /mnt/data/mariadb  # 서버(Node)의 실제 디렉토리에 저장
          type: DirectoryOrCreate