---
- name: 인벤토리 업데이트 (해당 서버 그룹)
  hosts: localhost
  become: yes
  tasks:
    - name: /etc/ansible/hosts에 IP 등록
      lineinfile:
        path: /etc/ansible/hosts
        line: "10.22.0.5" 
        insertafter: '^\[db_servers\]'  # 그룹명에 맞게 수정 (예: [db-servers])
        state: present
- name: MariaDB 서버 설치 및 Python 자동화 환경 구축
  hosts: db_servers
  become: yes
  vars:
    db_root_pw: "root"      
    db_name: "userdb"
    db_user: "root"
    db_ip: "10.22.0.4"

  tasks:
    - name: 1. MariaDB 관련 패키지 설치 (mariadb-server, python3-pymysql)
      dnf:
        name: [mariadb-server, mariadb, python3, python3-pip, python3-devel, gcc, python3-PyMySQL]
        state: present

    - name: 2. MariaDB 서비스 시작 및 활성화
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: 3. MariaDB 한글 인코딩 설정 (/etc/my.cnf.d/mariadb-server.cnf)
      blockinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf
        insertafter: '\[mariadb\]'
        block: |
          init_connect="SET collation_connection=utf8_general_ci"
          init_connect="SET NAMES utf8"
          character-set-server=utf8
          collation-server=utf8_general_ci

    - name: 4. 설정 적용을 위한 서비스 재시작
      service:
        name: mariadb
        state: restarted

    - name: 5. MariaDB root 비밀번호 설정
      ignore_errors: yes
      shell: |
        mariadb -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_root_pw }}'; FLUSH PRIVILEGES;"

    - name: 6. 필요한 Python 라이브러리 설치 (pip)
      pip:
        name: [pymysql, sqlalchemy, cryptography, python-multipart]
        state: present

    - name: 7. SSH 포트 확인 및 서비스 보장
      service:
        name: sshd
        state: started
        enabled: yes

    - name: 8. 배포 경로 생성 (/var/www/html)
      file:
        path: /var/www/html
        state: directory
        mode: '0755'