---
- name: 1. 인프라 기초 자동화 (VM - DNS & Mail)
  hosts: dns_mail_vms
  become: yes
  tasks:
    - name: DNS 서버 설정 실행
      import_tasks: dns_tasks.yaml
    - name: 메일 서버 설정 실행
      import_tasks: mail_tasks.yaml

- name: 2. 애플리케이션 현대화 (K8s - Web & DB)
  hosts: k8s_master
  become: yes
  tasks:
    - name: DB 서비스 및 파드 배포 (MariaDB)
      kubernetes.core.k8s:
        state: present
        definition:
          - apiVersion: v1
            kind: Service
            metadata:
              name: mariadb-service
            spec:
              selector:
                app: mariadb
              ports:
                - protocol: TCP
                  port: 3306
                  targetPort: 3306
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: mariadb
            spec:
              selector:
                matchLabels:
                  app: mariadb
              strategy:
                type: Recreate
              template:
                metadata:
                  labels:
                    app: mariadb
                spec:
                  containers:
                  - name: mariadb
                    image: mariadb:10.6
                    env:
                    - name: MARIADB_ROOT_PASSWORD
                      value: "root"
                    - name: MARIADB_DATABASE
                      value: "userdb"
                    ports:
                    - containerPort: 3306
                    volumeMounts:
                    - name: db-data
                      mountPath: /var/lib/mysql
                  volumes:
                  - name: db-data
                    hostPath:
                      path: /mnt/data/mariadb
                      type: DirectoryOrCreate

    - name: Web 서비스 및 파드 배포 (FastAPI)
      kubernetes.core.k8s:
        state: present
        definition:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: fastweb
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: fastapi
              template:
                metadata:
                  labels:
                    app: fastapi
                spec:
                  containers:
                  - name: fastapi
                    image: python:3.9-slim
                    command: ["python3", "main.py"]
                    ports:
                    - containerPort: 8000
                  dnsPolicy: "None"
                  dnsConfig:
                    nameservers:
                      - 10.22.0.3  
                    searches:
                      - kojel.com