---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-service
  namespace: db
  labels:
    app: mariadb-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-service
  template:
    metadata:
      labels:
        app: mariadb-service
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "P@ssw0rd"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: nfs-db-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: nfs-db-volume
        nfs:
          server: 10.15.0.170
          path: /root/nfs_node/db/ohit/db/sql
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: db
spec:
  selector:
    app: mariadb-service
  ports:
    - protocol: TCP
      port: 3306      # 서비스가 노출할 포트
      targetPort: 3306 # 파드 내부 컨테이너 포트
  type: ClusterIP