apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-was-yslee
  labels:
    service: was
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 10.15.0.170
    path: /root/nfs_node/was/yslee
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-was-yslee
  namespace: was
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-pv-was-yslee