apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-web-jjh
  labels:
    service: web
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 10.15.0.170
    path: /root/nfs_node/static
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-web-jjh
  namespace: web
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-pv-web-jjh
