apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-monitoring-prometheus
  labels:
    service: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 10.15.0.170
    path: /root/nfs_node/monitoring/prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-monitoring-prometheus
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-pv-monitoring-prometheus