apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-monitoring-kjs
  labels:
    service: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 10.15.0.170
    path: /root/nfs_node/monitoring/kjs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-monitoring-kjs
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-pv-monitoring-kjs