apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-web
  labels:
    service: web
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 10.15.0.170
    path: /root/nfs_node/static