---
- name: 메일 서버(Postfix/Dovecot) 자동 구축
  hosts: mail_servers
  become: yes
  tasks:
    - name: 1. DNS 설정 (방금 만든 DNS 서버 바라보기)
      copy:
        dest: /etc/resolv.conf
        content: "nameserver 192.168.17.3"

    - name: 2. 메일 패키지 설치
      dnf:
        name: [postfix, dovecot, mailx]
        state: present

    - name: 3. Postfix 설정 및 시작
      shell: |
        postconf -e "myhostname = mail.kojel.com"
        postconf -e "mydomain = kojel.com"
        postconf -e "myorigin = \$mydomain"
        postconf -e "inet_interfaces = all"
        systemctl restart postfix
        systemctl enable postfix

    - name: 4. Dovecot 설정 및 시작
      copy:
        dest: /etc/dovecot/dovecot.conf
        content: |
          protocols = imap pop3 lmtp submission
          disable_plaintext_auth = no
          ssl = no
          mail_location = mbox:~/mail:INBOX=/var/mail/%u

    - name: 5. Dovecot 서비스 시작
      service:
        name: dovecot
        state: restarted
        enabled: yes