apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-was
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      service: was