apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-config
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: config