apiVersion: v1 
kind: Secret 
metadata:
  name: user-lys-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "user-lys"
type: kubernetes.io/service-account.token
---
apiVersion: v1 
kind: Secret 
metadata:
  name: user-oit-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "user-oit"
type: kubernetes.io/service-account.token
---
apiVersion: v1 
kind: Secret 
metadata:
  name: user-jjh-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "user-jjh"
type: kubernetes.io/service-account.token
---
apiVersion: v1 
kind: Secret 
metadata:
  name: user-kjs-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "user-kjs"
type: kubernetes.io/service-account.token
