server {
    listen 80;
    server_name kojel.com www.kojel.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kojel.com www.kojel.com;
    charset utf-8;

    ssl_certificate /etc/nginx/ssl/tls.crt;
    ssl_certificate_key /etc/nginx/ssl/tls.key;

    location / {
        root /usr/share/nginx/html;
        index login.html;
    }

    location /api {
        proxy_pass http://localhost:8000/;

        # 리버스 프록시 핵심 헤더 설정
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}