# web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastweb
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: fastapi
        image: python:3.9-slim
        command: ["python3", "main.py"]
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 192.168.17.3  # 구축한 DNS 서버 IP
    searches:
      - kojel.com        