---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.22.0.3
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443

        volumeMounts:
        - name: config-vol
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nfs-static-volume
          mountPath: /usr/share/nginx/html
        - name: ssl-certs
          mountPath: "/etc/nginx/ssl"
          readOnly: true

      volumes:
      - name: config-vol
        nfs:
          server: 10.15.0.170
          path: /root/nfs_node/static/jjh/web/conf.d
      - name: nfs-static-volume
        nfs:
          server: 10.15.0.170
          path: /root/nfs_node/was/yslee/web_interface
      - name: ssl-certs
        secret:
          secretName: kojel-tls-secret

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
  annotations:
    metallb.io/loadBalancerIPs: 10.22.0.10
spec:
  type: LoadBalancer
  selector:
    app: web-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443