apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: web
data:
  default.conf: |
    server {
        listen 80;
        listen 443 ssl;
        server_name kojel.com www.kojel.com;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /api {
            proxy_pass http://localhost:8000/;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Kojel Web</title></head>
    <body style="text-align:center; padding-top:50px; background-color:#f4f4f4;">
        <h1> 웹 서버 가동 완료!</h1>
        <p>Namespace: web | MetalLB IP: 10.22.0.10</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastweb-combined
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      dnsPolicy: "None"  
      dnsConfig:
        nameservers:
          - 10.22.0.3    
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: config-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: ssl-certs
          mountPath: "/etc/nginx/ssl"
          readOnly: true
      - name: fastapi
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install fastapi uvicorn
            cat <<EOF > main.py
            from fastapi import FastAPI
            app = FastAPI()
            @app.get('/')
            def root():
                return {'message': 'Running!'}
            EOF
            uvicorn main:app --host 0.0.0.0 --port 8000
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: ssl-certs
        secret:
          secretName: kojel-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: web
  annotations:
    metallb.io/loadBalancerIPs: 10.22.0.10
spec:
  type: LoadBalancer
  selector:
    app: web-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


